Samman/Controllers/AutorisationController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Samman.DataBase;
using Samman.Models;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace Samman.Controllers
{
    public class AutorisationController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Undex()
        {
            return View();
        }

        public async Task<IActionResult> Registration(User model)
        {
            if (ModelState.IsValid)
            {
                // Проверяем, существует ли уже пользователь с таким именем
                using var db = new AccountDbContext();
                var existingUser = await db.Users.FirstOrDefaultAsync(u => u.Username == model.Username);
                if (existingUser != null)
                {
                    return RedirectToAction("LoginError", "Home");
                }

                // Проверяем длину имени пользователя
                if (model.Username.Length < 6)
                {
                    ModelState.AddModelError("Username", "Имя пользователя должно содержать не менее 6 символов.");
                    return RedirectToAction("LoginError", "Home");
                }

                // Хэширование пароля
                string hashedPassword = BCrypt.Net.BCrypt.HashPassword(model.Password);

                // Хэширование секретного ответа

                User user = new User
                {
                    Username = model.Username,
                    Password = hashedPassword,
                    Mail = model.Mail,
                    Gender = model.Gender
                };

                await db.Users.AddAsync(user);
                await db.SaveChangesAsync();

                // Остальной код

                var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Name, user.Username)
        };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                HttpContext.Session.SetString("Username", model.Username);
                HttpContext.Session.SetString("Gender", user.Gender);
                HttpContext.Session.SetInt32("IdUser", user.Id);

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("LoginError", "Home");
        }

        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                using var db = new AccountDbContext();

                // Найти пользователя по имени
                var user = await db.Users.FirstOrDefaultAsync(u => u.Username == model.Username);

                if (user != null)
                {
                    // Проверить хэш пароля
                    if (BCrypt.Net.BCrypt.Verify(model.Password, user.Password))
                    {
                        // Успешная аутентификация - установить данные пользователя в сессию
                        HttpContext.Session.SetString("Username", user.Username);
                        HttpContext.Session.SetInt32("IdUser", user.Id);
                        HttpContext.Session.SetString("Gender", user.Gender);

                        // Остальной код, если есть

                        var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Username)
            };

                        var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var principal = new ClaimsPrincipal(identity);

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                        // Остальной код, если есть

                        return RedirectToAction("Index", "Home");
                    }
                }

                ModelState.AddModelError(string.Empty, "Неверные имя пользователя или пароль");
                return RedirectToAction("LoginError", "Home");
            }

            return RedirectToAction("LoginError", "Home");
        }
    

        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Index", "Home");
        }
    }
}

Samman/Views/Autorisation/Index.cshtml
@{
    ViewData["Title"] = "Страница Регистрации";
    Layout = "";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Страница Регистрации</title>
    <link rel="stylesheet" type="text/css" href="~/css/auth.css">
</head>
<body>
    <div class="container">
        <h1>Регистрация</h1>
        <div class="d-flex flex-column align-items-center justify-content-center">
            <form id="registerForm" method="post" asp-controller="Autorisation" asp-action="Registration">
                <div class="form-group">
                    <label for="username">Имя пользователя</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <label for="gender">Пол</label>
                    <select class="form-control" id="gender" name="gender" required>
                        <option value="Мужчина">Мужчина</option>
                        <option value="Женщина">Женщина</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="Mail">Электронная почта</label>
                    <input type="text" class="form-control" id="secretAnswer" name="Mail" required>
                </div>
            </form>
            <a class="btn btn-primary mt-2 flash-button" style="font-family: Helvetica; width: 95%;" href="#" onclick="document.getElementById('registerForm').submit();">
                Зарегистрироваться
            </a>

        </div>
        <br />
        <form method="post" asp-controller="Autorisation" asp-action="Undex">
            <button class="btn btn-link mt-2 flash-button last" type="submit" style="font-size: 90%; background: none; border: none; cursor: pointer;">
                Уже имеете аккаунт?
            </button>
        </form>
    </div>
</body>
</html>

Samman/Views/Autorisation/Undex.cshtml
@{
    ViewData["Title"] = "Страница входа";
    Layout = "";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Страница Регистрации</title>
    <link rel="stylesheet" type="text/css" href="~/css/auth.css">
</head>
<body>
    <div class="container">
        <h1>Вход</h1>
        <div class="d-flex flex-column align-items-center justify-content-center">
            <form id="loginForm" asp-controller="Autorisation" asp-action="Login" method="post">
                <div class="form-group">
                    <label for="username">Имя пользователя</label>
                    <input type="text" class="form-control" id="username" name="Username" required>
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    <input type="password" class="form-control" id="password" name="Password" required>
                </div>
            </form>
            <a class="btn btn-primary mt-2 flash-button" style="font-family: Helvetica; width: 95%;" href="#" onclick="document.getElementById('loginForm').submit();">
                Войти
            </a>
        </div>
        <br />
        <form method="post" asp-controller="Home" asp-action="ForgotPasswordStep2">
            <button class="btn btn-link mt-2 flash-button last" type="submit" style="font-size: 90%; background: none; border: none; cursor: pointer;">
                Забыли пароль?
            </button>
        </form>
    </div>
</body>
</html>