Samman/Controllers/ArchivController.cs
using Microsoft.AspNetCore.Mvc;
using Samman.DataBase;
using Samman.Models;
using System.Net.Mime;

namespace Samman.Controllers
{
    public class ArchivController: Controller
    {
        public IActionResult ArchAdm()
        {
            return View();
        }

        public IActionResult ArchDown()
        {
            var model = new DocFileViewModel(); // Создайте экземпляр модели
            return View(model); // Передайте модель в представление
        }
        public IActionResult ArchViewer(int id)
        {
            var docFileDbContext = new Samman.DataBase.DocFileDbContext();

            var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);
            if (docFile != null)
            {
                return View(docFile);
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult ArchChange(int id)
        {
            var docFileDbContext = new Samman.DataBase.DocFileDbContext();

            var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);
            if (docFile != null)
            {
                return View(docFile);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult ArchAdd(DocFileViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var _docFileDbContext = new DocFileDbContext())
                    using (var _docNameDbContext = new DocNamesDbContext())
                    {
                        string docFileName = model.DocFileName;
                        byte[] docFileBytesPdf;
                        byte[] docFileBytesDoc;
                        byte[] docFileBytesJpg;
                        byte[] docFileBytesPng;

                        using (var memoryStream = new MemoryStream())
                        {

                            model.PdfFile?.CopyTo(memoryStream);
                            docFileBytesPdf = memoryStream.ToArray();
                        }
                        using (var memoryStream = new MemoryStream())
                        {

                            model.DocFile?.CopyTo(memoryStream);
                            docFileBytesDoc = memoryStream.ToArray();
                        }
                        using (var memoryStream = new MemoryStream())
                        {

                            model.JpgFile?.CopyTo(memoryStream);
                            docFileBytesJpg = memoryStream.ToArray();
                        }
                        using (var memoryStream = new MemoryStream())
                        {

                            model.PngFile?.CopyTo(memoryStream);
                            docFileBytesPng = memoryStream.ToArray();
                        }

                        var docFile = new DocFile
                        {
                            FileName = docFileName,
                            FileContentPDF = docFileBytesPdf,
                            FileContentDOC = docFileBytesDoc,
                            FileContentPNG = docFileBytesJpg,
                            FileContentJPG = docFileBytesPng,
                            DateCreated = model.DateCreate
                        };

                        _docFileDbContext.DocFile.Add(docFile);
                        _docFileDbContext.SaveChanges();

                        foreach (var category in model.Categores)
                        {
                            var archiveItem = new ArchiveItem
                            {
                                DocFilename = docFileName,
                                DocFileTruename = model.DocFileName,
                                Category = category,
                                DocFile = docFile
                            };
                            _docNameDbContext.DocNames.Add(archiveItem);
                        }

                        _docNameDbContext.SaveChanges();

                        return RedirectToAction("ArchAdm", "Services");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Произошла ошибка при сохранении данных: " + ex.Message);
                }
            }

            return View(model);
        }


        public IActionResult ArchRemove(int id)
        {

            using (var docFileDbContext = new DocFileDbContext())
            {
                var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);

                if (docFile != null)
                {
                    docFileDbContext.DocFile.Remove(docFile);
                    docFileDbContext.SaveChanges();

                    return RedirectToAction("Index", "Home");
                }

                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        public IActionResult Pdf(int id)
        {
            var docFileDbContext = new Samman.DataBase.DocFileDbContext();

            var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);

            if (docFile != null)
            {
                // Устанавливаем Content-Disposition заголовок в "inline" для отображения PDF в iframe
                Response.Headers.Add("Content-Disposition", new ContentDisposition
                {
                    Inline = true,
                    FileName = docFile.FileName + ".pdf"
                }.ToString());

                return File(docFile.FileContentPDF, "application/doc");
            }
            else
            {
                // Обработка случая, если файл не найден
                return NotFound();
            }
        }
        [HttpGet]
        public IActionResult Doc(int id)
        {
            var docFileDbContext = new Samman.DataBase.DocFileDbContext();

            var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);

            if (docFile != null)
            {
                // Устанавливаем Content-Disposition заголовок в "inline" для отображения PDF в iframe
                Response.Headers.Add("Content-Disposition", new ContentDisposition
                {
                    Inline = true,
                    FileName = docFile.FileName + ".doc"
                }.ToString());

                return File(docFile.FileContentDOC, "application/doc");
            }
            else
            {
                // Обработка случая, если файл не найден
                return NotFound();
            }
        }
        [HttpGet]
        public IActionResult Jpg(int id)
        {
            var docFileDbContext = new Samman.DataBase.DocFileDbContext();

            var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);

            if (docFile != null)
            {
                // Устанавливаем Content-Disposition заголовок в "inline" для отображения PDF в iframe
                Response.Headers.Add("Content-Disposition", new ContentDisposition
                {
                    Inline = true,
                    FileName = docFile.FileName + ".jpg"
                }.ToString());

                return File(docFile.FileContentJPG, "application/doc");
            }
            else
            {
                // Обработка случая, если файл не найден
                return NotFound();
            }
        }
        [HttpGet]
        public IActionResult Png(int id)
        {
            var docFileDbContext = new Samman.DataBase.DocFileDbContext();

            var docFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.Id == id);

            if (docFile != null)
            {
                // Устанавливаем Content-Disposition заголовок в "inline" для отображения PDF в iframe
                Response.Headers.Add("Content-Disposition", new ContentDisposition
                {
                    Inline = true,
                    FileName = docFile.FileName + ".png"
                }.ToString());

                return File(docFile.FileContentPNG, "application/doc");
            }
            else
            {
                // Обработка случая, если файл не найден
                return NotFound();
            }
        }
    }
}

Samman/Views/Archiv/ArchAdm.cshtml
@model IEnumerable<Samman.Models.DocFile>

@{
    ViewData["Title"] = "Список PDF-файлов";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Подключение стилей -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/archiv.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Manchkin.styles.css" asp-append-version="true" />

    <!-- Добавление стилей для анимации загрузки -->
    <style>
        .loading-container {
            display: flex;
            justify-content: center;
            align-items: center;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(255, 255, 255, 0.8);
            z-index: 9999;
        }

        .loading-animation {
            width: 100px;
            height: 100px;
            border: 10px solid #f3f3f3;
            border-top: 10px solid #3498db;
            border-radius: 50%;
            animation: spin 2s linear infinite;
        }

        /* Скроем контент страницы при загрузке */
        body {
            overflow: hidden;
        }
    </style>
</head>
<body class="content-archiv">
    <div id="content-window">
    <div class="text-center">
        <h1>Архив электронных проектных документов</h1>
        <br />
        <h1 style="font-size: 75%;">Этот архив - ключ к миру исключительной организации и эффективности в проектной работе. Внимательно хранимые здесь электронные проектные документы - это не просто файлы, это капитал знаний и опыта нашей команды. Здесь мы собрали лучшие идеи, творческие находки и трудные уроки, которые помогут нам двигаться вперед, достигая новых высот в наших проектах. Пусть этот архив станет нашим верным компаньоном в стремлении к новым вершинам достижений.</h1>
    </div>

        <div class="container">
            <form method="get" action="">
                <div class="row">
                    <div class="col-md-2">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="search" placeholder="Поиск по имени файла" value="@Context.Request.Query["search"].ToString()">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="input-group mb-3">
                            <input type="number" class="form-control" name="filterYear" placeholder="Фильтр по году" value="@Context.Request.Query["filterYear"].ToString()">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" name="searchCategory" placeholder="Поиск по категории" value="@Context.Request.Query["searchCategory"].ToString()">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">Применить</button>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="input-group-append">
                            <a class="btn btn-primary" href="/Archiv/ArchDown" type="submit">Добавить</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>

    <div class="table-scrollable">
        <table class="table table-bordered" id="pdfTable">
            <thead>
                <tr>
                    <th>Имя файла</th>
                    <th>Дата создания</th>
                    <th class="category-column">Категория</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var searchQuery = Context.Request.Query["search"].ToString();
                    var docNameDbContext = new Samman.DataBase.DocNamesDbContext();
                    var docFileDbContext = new Samman.DataBase.DocFileDbContext();
                    var searchCategoryQuery = Context.Request.Query["searchCategory"].ToString();
                    var filterYear = Context.Request.Query["filterYear"].ToString();

                    var matchingArchiveItems = docNameDbContext.DocNames.AsQueryable();

                    if (!string.IsNullOrEmpty(searchQuery))
                    {
                        matchingArchiveItems = matchingArchiveItems.Where(ai => ai.DocFileTruename.Contains(searchQuery));
                    }

                    if (!string.IsNullOrEmpty(searchCategoryQuery))
                    {
                        matchingArchiveItems = matchingArchiveItems.Where(ai => ai.Category.Contains(searchCategoryQuery));
                    }

                    if (!string.IsNullOrEmpty(filterYear) && int.TryParse(filterYear, out var year))
                    {
                        matchingArchiveItems = matchingArchiveItems.Where(ai =>
                        (ai.DocFile != null && ai.DocFile.DateCreated.Year == year)
                        || (ai.DocFile == null && docFileDbContext.DocFile.Any(pf => pf.FileName == ai.DocFilename && pf.DateCreated.Year == year)));
                    }

                    var filteredArchiveItems = matchingArchiveItems.ToList();
                }
                @foreach (var archiveItem in filteredArchiveItems)
                {
                    <tr>
                        <td>@archiveItem.DocFileTruename</td>

                        <td>
                            @{
                                if (archiveItem.DocFile != null)
                                {
                                    @archiveItem.DocFile.DateCreated.ToString("dd.MM.yyyy")
                                }
                                else if (!string.IsNullOrEmpty(archiveItem.DocFilename))
                                {
                                    var pdfile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.FileName == archiveItem.DocFilename);
                                    if (pdfile != null)
                                    {
                                        @pdfile.DateCreated.ToString("dd.MM.yyyy")
                                    }
                                    else
                                    {
                                        <span class="text-danger">Дата не доступна</span>
                                    }
                                }
                                else
                                {
                                    <span class="text-danger">Дата не доступна</span>
                                }
                            }
                        </td>

                        <td class="category-cell">@archiveItem.Category</td>

                        <!-- Apply the "button-cell" class to center buttons -->
                        <td class="button-cell">
                            @{
                                var pdfFile = docFileDbContext.DocFile.FirstOrDefault(pf => pf.FileName == archiveItem.DocFilename);
                                if (pdfFile != null)
                                {
                                        <a href="@Url.Action("ArchChange", "Archiv", new { id = pdfFile.Id })" target="_blank" class="btn btn-primary">Изменить</a>
                                }
                                else
                                {
                                    <span class="text-danger">PDF-файл не найден</span>
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function applyYearFilter() {
            var filterYear = document.getElementById("filterYear").value;
            var table = document.getElementById("pdfTable");
            var rows = table.getElementsByTagName("tr");

            for (var i = 1; i < rows.length; i++) {
                var row = rows[i];
                var cell = row.getElementsByTagName("td")[1];
                if (cell) {
                    var date = cell.textContent.trim();
                    var year = parseInt(date.split(".")[2]);
                    if (year !== parseInt(filterYear)) {
                        row.style.display = "none";
                    } else {
                        row.style.display = "";
                    }
                }
            }
        }
    </script>
</body>
</html>

Samman/Views/Archiv/ArchChange.cshtml
@model Samman.Models.DocFile

<div class="pdf-buttons">
    <a href="@Url.Action("ArchRebuild", "Archiv", new { id = Model.Id })" target="_blank" class="pdf-button">Изменить данные</a>
    <a href="@Url.Action("ArchRemove", "Archiv", new { id = Model.Id })" target="_blank" class="pdf-button">Удалить все данные</a>
</div>

Samman/Views/Archiv/ArchDown.cshtml
@model Samman.Models.DocFileViewModel

@{
    ViewData["Title"] = "Добавить PDF-файл";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="post" enctype="multipart/form-data" asp-controller="Archiv" asp-action="ArchAdd">
                <div class="form-group">
                    <label asp-for="DocFileName">Название документа:</label>
                    <input asp-for="DocFileName" class="form-control" />
                    <span asp-validation-for="DocFileName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">PDF-файл:</label>
                    <input type="file" name="PdfFile" class="form-control-file" />
                    <span asp-validation-for="PdfFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">DOC-файл:</label>
                    <input type="file" name="DocFile" class="form-control-file" />
                    <span asp-validation-for="DocFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">JPG-файл:</label>
                    <input type="file" name="JpgFile" class="form-control-file" />
                    <span asp-validation-for="JpgFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">PNG-файл:</label>
                    <input type="file" name="PngFile" class="form-control-file" />
                    <span asp-validation-for="PngFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateCreate">Время:</label>
                    <input asp-for="DateCreate" type="datetime-local" class="form-control" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}" />
                    <span asp-validation-for="DateCreate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Categores">Категория:</label>
                    <select asp-for="Categores" multiple class="form-control">
                        <option value="Протокол">Протокол</option>
                        <option value="Документ">Документ</option>
                        <option value="Соглашение">Соглашение</option>
                        <option value="Заявление">Заявление</option>
                        <option value="Решение">Решение</option>
                        <option value="Устав">Устав</option>
                        <option value="Сведения">Сведения</option>
                        <option value="Лицензия">Лицензия</option>
                        <option value="Доверенность">Доверенность</option>
                        <option value="Закон">Закон</option>
                        <option value="Положение">Положение</option>
                        <option value="Смета">Смета</option>
                        <option value="План">План</option>
                    </select>
                    <span asp-validation-for="Categores" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
            </form>
        </div>
    </div>
</div>

Samman/Views/Archiv/ArchRebuild.cshtml
@model Samman.Models.DocFileViewModel

@{
    ViewData["Title"] = "Изменить PDF-файл";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="post" enctype="multipart/form-data" asp-controller="Archiv" asp-action="ArchNews"> 
                <input type="hidden" asp-for="Id" value="@Model.Id" />
                <div class="form-group">
                    <label asp-for="DocFileName">Название документа:</label>
                    <input asp-for="DocFileName" class="form-control" />
                    <span asp-validation-for="DocFileName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">PDF-файл:</label>
                    <input type="file" name="PdfFile" class="form-control-file" />
                    <span asp-validation-for="PdfFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">DOC-файл:</label>
                    <input type="file" name="DocFile" class="form-control-file" />
                    <span asp-validation-for="DocFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">JPG-файл:</label>
                    <input type="file" name="JpgFile" class="form-control-file" />
                    <span asp-validation-for="JpgFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DocFile">PNG-файл:</label>
                    <input type="file" name="PngFile" class="form-control-file" />
                    <span asp-validation-for="PngFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateCreate">Время:</label>
                    <input asp-for="DateCreate" type="datetime-local" class="form-control" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}" />
                    <span asp-validation-for="DateCreate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Categores">Категория:</label>
                    <select asp-for="Categores" multiple class="form-control">
                        <option value="Протокол">Протокол</option>
                        <option value="Документ">Документ</option>
                        <option value="Соглашение">Соглашение</option>
                        <option value="Заявление">Заявление</option>
                        <option value="Решение">Решение</option>
                        <option value="Устав">Устав</option>
                        <option value="Сведения">Сведения</option>
                        <option value="Лицензия">Лицензия</option>
                        <option value="Доверенность">Доверенность</option>
                        <option value="Закон">Закон</option>
                        <option value="Положение">Положение</option>
                        <option value="Смета">Смета</option>
                        <option value="План">План</option>
                    </select>
                    <span asp-validation-for="Categores" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
            </form>
        </div>
    </div>
</div>

Samman/Views/Archiv/ArchViewer.cshtml
@model Samman.Models.DocFile

<div class="pdf-buttons">
    <a href="@Url.Action("Pdf", "Archiv", new { id = Model.Id })" target="_blank" class="pdf-button">Открыть PDF</a>
    <a href="@Url.Action("Docx", "Archiv", new { id = Model.Id })" target="_blank" class="pdf-button">Скачать DOC</a>
    <a href="@Url.Action("Png", "Archiv", new { id = Model.Id })" target="_blank" class="pdf-button">Открыть PNG</a>
    <a href="@Url.Action("Jpg", "Archiv", new { id = Model.Id })" target="_blank" class="pdf-button">Открыть JPG</a>
</div>